# -*- coding: utf-8 -*-
"""
hr_payslip_portal.py
====================
Thin extension that adds a helper used by the payslip download route.
The actual PDF is generated by Odoo's standard QWeb report engine
(``hr_payroll.action_report_payslip``); this model adds no new fields.
"""

from odoo import models


class HrPayslipPortal(models.Model):
    _inherit = 'hr.payslip'

    def _ess_can_portal_user_access(self):
        """Return True iff the current portal user owns this payslip and it's finalized."""
        self.ensure_one()
        return (
            self.employee_id.user_id == self.env.user
            and self.state in ('done', 'paid')
        )
